import time from "./timer.js"
import control from "./controls.js"
import sounds from "./sounds.js"
import event from "./events.js"

import {
   buttonPlay,
   buttonPause,
   buttonStop,
   buttonSet,
   buttonUp,
   buttonDown,
   buttonFlorestPlay,
   buttonFlorestPause,
   buttonRainPlay,
   buttonRainPause,
   buttonCoffePlay,
   buttonCoffePause,
   buttonFirePlay,
   buttonFirePause,
   minutesDisplay,
   secondDisplay,
   body,
   letters,
   inpFlorest,
   inpRain,
   inpCoffe,
   inpFire,
   imgFlorest,
   imgFlorestDarkMode,
   imgRain,
   imgRainDarkMode,
   imgCoffe,
   imgCoffeDarkMode,
   imgFire,
   imgFireDarkMode,
   imgButtonPlay,
   imgButtonPause,
   imgButtonStop,
   imgButtonSet,
   imgButtonUp,
   imgButtonDown,
   imgButtonPlayDarkMode,
   imgButtonPauseDarkMode,
   imgButtonStopDarkMode,
   imgButtonSetDarkMode,
   imgButtonUpDarkMode,
   imgButtonDownDarkMode,
   buttonSun,
   buttonMoon
} from "./elements.js"

const sound = sounds()

const controls = control({
   buttonPlay,
   buttonPause,
   buttonStop,
   buttonSet,
   buttonUp,
   buttonDown,
   buttonFlorestPlay,
   buttonFlorestPause,
   buttonRainPlay,
   buttonRainPause,
   buttonCoffePlay,
   buttonCoffePause,
   buttonFirePlay,
   buttonFirePause,
   body,
   letters,
   inpFlorest,
   inpRain,
   inpCoffe,
   inpFire,
   imgFlorest,
   imgFlorestDarkMode,
   imgRain,
   imgRainDarkMode,
   imgCoffe,
   imgCoffeDarkMode,
   imgFire,
   imgFireDarkMode,
   imgButtonPlay,
   imgButtonPause,
   imgButtonStop,
   imgButtonSet,
   imgButtonUp,
   imgButtonDown,
   imgButtonPlayDarkMode,
   imgButtonPauseDarkMode,
   imgButtonStopDarkMode,
   imgButtonSetDarkMode,
   imgButtonUpDarkMode,
   imgButtonDownDarkMode,
   buttonSun,
   buttonMoon,
})

const timer = time({
   secondDisplay,
   minutesDisplay,
   controls,
   buttonUp,
   buttonDown,
})

event({
   controls,
   sound,
   timer,
})



